name: Pre Merge Checks
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  ktlint:
    runs-on: [ubuntu-latest]
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Gradle Folders
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle

      - name: Run ktlint
        run: ./gradlew ktlintCheck

  detekt:
    runs-on: [ubuntu-latest]
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Gradle Folders
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle

      - name: Run detekt
        run: ./gradlew detekt

  test:
    runs-on: [ubuntu-latest]
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Gradle Folders
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle

      - name: Run all the tests
        run: ./gradlew test

  build-debug-apk:
    strategy:
      fail-fast: false
      matrix:
        agp: [""]
        kotlin: [""]
        experimental: [false]
        include:
          - agp: 4.2.0-alpha14
            experimental: true
          - kotlin: 1.4.20-M2
            experimental: true

    runs-on: [ubuntu-latest]
    continue-on-error: ${{ matrix.experimental }}
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      VERSION_AGP: ${{ matrix.agp }}
      VERSION_KOTLIN: ${{ matrix.kotlin }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Gradle Folders
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle

      - name: Build the Debug APK
        run: ./gradlew assembleDebug

      - uses: actions/upload-artifact@v2
        with:
          name: appintro-sample-app.apk
          path: example/build/outputs/apk/debug/example-debug.apk
